name: Build and Deploy Website with Ansible

on:
  push:
    branches:
      - main
jobs:
  build_and_deploy:
    runs-on: [self-hosted, Linux]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2  # Checkout the repository code
    - name: Set up the counter
      run: |
        cd /home/adi/demo/basicwebapp/actions-runner
        COUNTER_FILE=".counter"
        if [ -f "$COUNTER_FILE" ]; then
          COUNTER=$(cat "$COUNTER_FILE")
        else
          COUNTER=1
        fi
          NEWTAG=$((COUNTER + 1))
          echo $NEWTAG > .counter
          echo "Counter value is: $COUNTER.0"
          echo "NEWTAG value is: $NEWTAG.0"
          echo "Counter=$COUNTER" >> $GITHUB_ENV
          echo "NEWTAG=$NEWTAG" >> $GITHUB_ENV
          echo $(whoami)
          echo $(pwd)
          
    - name: Build Docker image
      run: |
        cd basicwebapp/actions-runner/
        sudo docker build -t webapp:${NEWTAG}.0 .

    - name: Push Docker image to Docker Hub 
      run: |
         sudo docker tag webapp:$NEWTAG.0 adiyehie/webapp:$NEWTAG.0    
         sudo docker login -u "${{ secrets.DOCKERHUBUSERNAME }}" -p "${{ secrets.DOCKERHUBTOKEN }}" 
         sudo docker push adiyehie/webapp:$NEWTAG.0

    - name: Run Ansible Playbook for Deployment
      run: |
        
        cd /home/adi/demo/basicwebapp/actions-runner
        # Change image get in the playbook
        echo "Counter value is: $COUNTER.0"
        echo "NEWTAG value is: $NEWTAG.0"
        sed -i "s/webapp:${COUNTER}.0/webapp:${NEWTAG}.0/g" deploy-playbook.yml
        # Run the Ansible playbook to deploy to the VM
        ansible-playbook -i inventory.ini deploy-playbook.yml -u vagrant
