name: Build and Deploy Website with Ansible

on:
  push:
    branches:
      - main
jobs:
  build_and_deploy:
    runs-on: [self-hosted, Linux]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2  # Checkout the repository code
    - name: Set up the counter
      run: |
        COUNTER_FILE=".counter"
        if [ -f "$COUNTER_FILE" ]; then
          COUNTER=$(cat "$COUNTER_FILE")
        else
          COUNTER=1
        fi
          NEWTAG=$((COUNTER + 1))
           echo $NEWTAG >> .counter
          echo "Counter value is: $COUNTER"
          echo "Counter=$COUNTER" >> $GITHUB_ENV
          echo $(whoami)
          
    - name: Build Docker image
      run: |
        sudo docker build -t webapp:$NEWTAG .

    - name: Push Docker image to Docker Hub 
      run: |
        sudo docker tag webapp:$NEWTAG adiyehie/webapp:$NEWTAG
        sudo docker push webapp:$NEWTAG

    - name: Run Ansible Playbook for Deployment
      run: |
        # Change image get in the playbook
        sed -i "s/webapp:${COUNTER}.0/webapp:${NEWTAG}.0/g" deploy-playbook.yml
        # Run the Ansible playbook to deploy to the VM
        ansible-playbook -i inventory.ini deploy-playbook.yml
