name: Build and Deploy Website with Ansible

on:
  push:
    branches:
      - main
jobs:
  build_and_deploy:
    runs-on: [self-hosted, Linux]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2  # Checkout the repository code
    - name: Set up the counter
      run: |
        COUNTER_FILE=".counter"
        if [ -f "$COUNTER_FILE" ]; then
          COUNTER=$(cat "$COUNTER_FILE")
        else
          COUNTER=1
        fi
          NEWTAG=$((COUNTER + 1))
          echo $NEWTAG > .counter
          echo "Counter value is: $COUNTER"
          echo "NEWTAG value is: $NEWTAG.0"
          echo "Counter=$COUNTER" >> $GITHUB_ENV
          echo "NEWTAG=$NEWTAG" >> $GITHUB_ENV
          echo $(whoami)
          echo $(pwd)
          
    - name: Build Docker image
      run: |
        cd basicwebapp/actions-runner/
        sudo docker build -t webapp:${NEWTAG}.0 .

    - name: Push Docker image to Docker Hub 
      run: |
        echo "${{ secrets.DOCKERHUBUSERNAME }} ${{ secrets.DOCKERHUBTOKEN }}"
        sudo docker tag webapp:$NEWTAG.0 adiyehie/webapp:$NEWTAG.0
        if [ -z "${{ secrets.DOCKERHUBUSERNAME }}" ]; then echo "DOCKERHUBUSERNAME is empty"; else echo "DOCKERHUBUSERNAME is set"; fi
        echo ${{ secrets.DOCKERHUBTOEKN }} > filecheck
        sudo docker push webapp:$NEWTAG.0

    - name: Run Ansible Playbook for Deployment
      run: |
        # Change image get in the playbook
        sed -i "s/webapp:${COUNTER}.0/webapp:${NEWTAG}.0/g" deploy-playbook.yml
        # Run the Ansible playbook to deploy to the VM
        ansible-playbook -i inventory.ini deploy-playbook.yml
